  base_frame : "base_link"

  map_frame  : "map"

  odom_frame : "odom"

  map_update_interval   : 2.0
  # How long (in seconds) between updates to the map. Lowering this number updates the occupancy grid more often, at the expense of greater computational load.

  maxUrange : 80
  # The maximum usable range of the laser. A beam is cropped to this value. 

  sigma : 0.05
  #The sigma used by the greedy endpoint matching 

  kernelSize : 1
  #The kernel in which to look for a correspondence 

  lstep : 0.05
  #The optimization step in translation 

  astep : 0.05
  #The optimization step in rotation 

  iterations : 5
  #The number of iterations of the scanmatcher 

  #lsigma : 0.075
  #The sigma of a beam used for likelihood computation 

  ogain : 3.0
  #Gain to be used while evaluating the likelihood, for smoothing the resampling effects 

  #lskip : 0 
  #Number of beams to skip in each scan. 

  #minimumScore : 0.0
  #Minimum score for considering the outcome of the scan matching good. Can avoid jumping pose estimates in large open spaces when using laser scanners with limited range (e.g. 5m). Scores go up to 600' #try 50 for example when experiencing jumping estimate issues. 

  #srr : 0.1
  #Odometry error in translation as a function of translation (rho/rho) 

  #srt : 0.2
  #Odometry error in translation as a function of rotation (rho/theta) 

  #str : 0.1
  #Odometry error in rotation as a function of translation (theta/rho) 

  #stt : 0.2
  #Odometry error in rotation as a function of rotation (theta/theta) 

  linearUpdate : 0.5
  #Process a scan each time the robot translates this far 

  angularUpdate : 0.5
  #Process a scan each time the robot rotates this far 

  temporalUpdate : -1.0
  #Process a scan if the last scan processed is older than the update time in seconds. A value less than zero will turn time based updates off. 

  #resampleThreshold : 0.5
  #The Neff based resampling threshold 

  particles : 50
  #Number of particles in the filter. Particles changed from default value 30 to 80. 

  #xmin : -100.0
  #Initial map size 

  #ymin : 100.0
  #Initial map size 

  #xmax : 100.0
  #Initial map size 

  #ymax : 100.0
  #Initial map size 

  delta : 0.05
  #Resolution of the map.

  #llsamplerange : 0.01
  #Translational sampling range for the likelihood 

  #llsamplestep : 0.01
  #Translational sampling step for the likelihood 

  #lasamplerange : 0.005
  #Angular sampling range for the likelihood 

  #lasamplestep : 0.005
  #Angular sampling step for the likelihood 

  transform_publish_period : 0.05
  #How long (in seconds) between transform publications. 

  occ_thresh : 0.25
  #Threshold on gmapping's occupancy values. Cells with greater occupancy are considered occupied (i.e., set to 100 in the resulting sensor_msgs/LaserScan). New in 1.1.0. 

  #maxRange :(float)
  #The maximum range of the sensor. If regions with no obstacles within the range of the sensor should appear as free space in the map, set maxUrange < maximum range of the real sensor <= maxRan


