footprint: [[0.50,0.50],[-0.50,0.50],[-0.50,-0.50],[0.50,-0.50]]

inflation_layer:
  inflation_radius: 1
  cost_scaling_factor: 5

# Please uncomment or additional lasers based on your requirements
observation_sources: lidar_1 #lidar_2

# Uncomment below when using light_scan
# lidar_1: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: /light_scan, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}

# For normal gazebo world
lidar_1: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: /lidar_1/scan_filtered, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}

# lidar_2: {sensor_frame: lidar_2_link , data_type: LaserScan, topic: lidar_2/scan_filtered, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}

