footprint: [[0.50,0.50],[-0.50,0.50],[-0.50,-0.50],[0.50,-0.50]]

inflation_layer:
  inflation_radius: 1
  cost_scaling_factor: 5

observation_sources: lidar_1

lidar_1: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: lidar_1/scan_filtered, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}

