obstacle_range: 2
raytrace_range: 2.0
footprint: [[0.5,0.4],[-0.5,0.4],[-0.5,-0.4],[0.5,-0.4]]
inflation_radius: 2.3
cost_scaling_factor: 10.0

observation_sources: laser_scan_front laser_scan_back 

laser_scan_front: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: lidar_1/scan_filtered, marking: true, clearing: true}


laser_scan_back: {sensor_frame: lidar_2_link , data_type: LaserScan, topic: lidar_2/scan_filtered, marking: true, clearing: true}



