local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 1
  static_map: false
  rolling_window: true
  max_obstacle_width: 8.0
  max_obstacle_height: 8.0
  width: 5
  height: 5
  resolution: 0.1
  transfrom_tolerance: 0.5
