obstacle_range: 2
raytrace_range: 2.0
footprint: [[0.30,0.30],[-0.30,0.30],[-0.30,-0.30],[0.30,-0.30]]
inflation_radius: 2.3
cost_scaling_factor: 10.0

observation_sources: laser_scan_front

laser_scan_front: {sensor_frame: laser_1_link , data_type: LaserScan, topic: /lidar_1/scan_filtered, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}



